"""Global exception handlers for the Aura framework."""

from __future__ import annotations

import logging
from typing import Any

from pydantic import ValidationError as PydanticValidationError
from starlette.requests import Request
from starlette.responses import JSONResponse, Response

from aura.exceptions.http import HTTPException, InternalServerException

logger = logging.getLogger("aura.exceptions")


async def exception_handler(request: Request, exc: Exception) -> Response:
    """
    Global exception handler attached to the Starlette application.

    Handles:
    - :class:`~aura.exceptions.http.HTTPException` subclasses → structured
      JSON response with the appropriate status code.
    - :class:`pydantic.ValidationError` → 422 with field-level error details.
    - Any other :class:`Exception` → 500 (details are logged, not exposed).

    Args:
        request: The incoming HTTP request.
        exc: The exception that was raised.

    Returns:
        A :class:`~starlette.responses.JSONResponse` with the error payload.
    """
    if isinstance(exc, HTTPException):
        return JSONResponse(
            content=exc.to_dict(),
            status_code=exc.status_code,
            headers=exc.headers,
        )

    if isinstance(exc, PydanticValidationError):
        return await validation_exception_handler(request, exc)

    # Unexpected error — log and return a generic 500
    logger.exception("Unhandled exception during request to %s", request.url)
    server_error = InternalServerException()
    return JSONResponse(
        content=server_error.to_dict(),
        status_code=500,
    )


async def validation_exception_handler(
    request: Request,
    exc: PydanticValidationError,
) -> JSONResponse:
    """
    Convert a :class:`pydantic.ValidationError` into a 422 JSON response.

    The response body matches the OpenAPI ``HTTPValidationError`` schema
    generated by :class:`~aura.schema.openapi.OpenAPIGenerator`.

    Args:
        request: The incoming HTTP request (unused but required by Starlette).
        exc: The Pydantic validation error.

    Returns:
        A :class:`~starlette.responses.JSONResponse` with status 422 and
        field-level error details.
    """
    errors: list[dict[str, Any]] = []
    for error in exc.errors():
        errors.append(
            {
                "loc": list(error["loc"]),
                "msg": error["msg"],
                "type": error["type"],
            }
        )
    return JSONResponse(
        content={"detail": errors},
        status_code=422,
    )
