"""Alembic integration helpers for Aura ORM migrations."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from typing import Any


def get_alembic_config(
    migrations_dir: str | Path = "migrations",
    database_url: str | None = None,
) -> Any:
    """Build and return an Alembic :class:`~alembic.config.Config` object.

    Args:
        migrations_dir: Path to the Alembic migrations directory.
        database_url: Override the ``sqlalchemy.url`` config option.
                      If ``None``, the value from ``alembic.ini`` is used.

    Returns:
        An Alembic Config instance ready for programmatic use.

    Raises:
        ImportError: If Alembic is not installed.
    """
    try:
        from alembic.config import Config
    except ImportError as exc:
        raise ImportError(
            "Alembic is required for migrations. "
            "Install with: pip install aura-framework[sqlalchemy]"
        ) from exc

    migrations_path = Path(migrations_dir).resolve()
    ini_file = migrations_path.parent / "alembic.ini"

    config = Config(str(ini_file) if ini_file.exists() else None)
    config.set_main_option("script_location", str(migrations_path))

    if database_url:
        config.set_main_option("sqlalchemy.url", database_url)

    return config


def run_migrations_offline(target_metadata: Any, url: str) -> None:
    """Run migrations in 'offline' mode (generates SQL without a live connection).

    Intended to be called from the Alembic ``env.py`` file.

    Args:
        target_metadata: The SQLAlchemy metadata to migrate.
        url: The database URL.
    """
    try:
        from alembic import context as alembic_context
    except ImportError as exc:
        raise ImportError("Alembic not installed") from exc

    alembic_context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with alembic_context.begin_transaction():
        alembic_context.run_migrations()


async def run_migrations_online(target_metadata: Any, engine: Any) -> None:
    """Run migrations in 'online' mode using an async engine.

    Intended to be called from the Alembic ``env.py`` file.

    Args:
        target_metadata: The SQLAlchemy metadata to migrate.
        engine: An async SQLAlchemy engine.
    """
    try:
        from alembic import context as alembic_context
        from sqlalchemy.ext.asyncio import AsyncConnection
    except ImportError as exc:
        raise ImportError("Alembic / SQLAlchemy not installed") from exc

    async with engine.connect() as connection:
        await connection.run_sync(
            lambda sync_conn: alembic_context.configure(
                connection=sync_conn,
                target_metadata=target_metadata,
            )
        )
        async with connection.begin():
            await connection.run_sync(lambda _: alembic_context.run_migrations())


def generate_env_py(migrations_dir: Path, model_import: str) -> str:
    """Generate the content for an Alembic ``env.py`` file.

    Args:
        migrations_dir: Directory where the file will be placed.
        model_import: Python import path to the application's AuraModel base,
                      e.g. ``"myapp.models:Base"``.

    Returns:
        String content for ``env.py``.
    """
    module, attr = model_import.split(":")
    return f'''\
"""Alembic env.py — generated by Aura CLI."""
from __future__ import annotations

import asyncio
from logging.config import fileConfig

from sqlalchemy.ext.asyncio import create_async_engine

from alembic import context

# Import your application's models so Alembic can detect schema changes.
from {module} import {attr} as target_metadata_base

target_metadata = target_metadata_base.metadata

config = context.config
if config.config_file_name:
    fileConfig(config.config_file_name)


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={{"paramstyle": "named"}},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection):
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    url = config.get_main_option("sqlalchemy.url")
    engine = create_async_engine(url)
    async with engine.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await engine.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''
