"""``aura generate`` — scaffold modules, controllers, services, schemas, guards."""

from __future__ import annotations

import re
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

app = typer.Typer(help="Generate Aura resources.")
console = Console()


# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------

def _snake(name: str) -> str:
    name = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    return re.sub(r"[-\s]+", "_", name).lower()

def _pascal(name: str) -> str:
    return "".join(w.capitalize() for w in re.split(r"[-_\s]+", name))

def _plural(name: str) -> str:
    s = _snake(name)
    return s if s.endswith("s") else s + "s"


# ---------------------------------------------------------------------------
# File content generators
# ---------------------------------------------------------------------------

def _schemas(name: str) -> str:
    p, s, _ = _pascal(name), _snake(name), _plural(name)
    return f'''\
"""Schemas (Spec) for the {p} module.

Schemas are the source of truth in Aura (SDD — Spec-Driven Development).
The framework derives validation, serialisation and OpenAPI docs from them.
"""
from __future__ import annotations

from aura import Schema


class Create{p}DTO(Schema):
    """Fields required to create a new {s}."""
    name: str


class Update{p}DTO(Schema):
    """Partial update — all fields optional."""
    name: str | None = None


class {p}Response(Schema):
    """What the API returns for a {s}."""
    id:   int
    name: str
'''


def _factory(name: str) -> str:
    p = _pascal(name)
    return f'''\
"""Factory for the {p} model.

Generated by Aura CLI.
"""
from __future__ import annotations

from typing import Any

from aura.orm import Factory
# Import your model here, e.g.:
# from app.models import {p}


class {p}Factory(Factory[Any]):  # Replace Any with your {p} model class
    # model = {p}

    def definition(self) -> dict[str, Any]:
        return {{
            # Define your model default attributes here, e.g.:
            # "name": lambda: self.faker.name(),
            # "email": lambda: self.faker.unique.email(),
        }}
'''


def _models(name: str) -> str:
    p, _, pl = _pascal(name), _snake(name), _plural(name)
    return f'''\
"""ORM model for the {p} module.

Uncomment when adding database persistence.
Requires: pip install "aura-web[sqlalchemy]"
"""
from __future__ import annotations

# from aura.orm import AuraModel, CharField, EmailField
# from sqlalchemy.orm import Mapped
#
#
# class {p}(AuraModel):
#     # __tablename__ = "{pl}"
#
#     # name: Mapped[str] = CharField(max_length=150)
#     # email: Mapped[str | None] = EmailField(required=False, unique=True)
'''


def _repository(name: str) -> str:
    p, _, _pl = _pascal(name), _snake(name), _plural(name)
    return f'''\
"""Repository for the {p} module.

Uncomment when adding database persistence.
Configure the ORM model in models.py first.
"""
from __future__ import annotations

# from aura.orm import Repository
# from .models import {p}
#
#
# class {p}Repository(Repository[{p}]):
#     model = {p}
#
#     # Add custom queries here, e.g.:
#     # async def find_by_name(self, name: str) -> {p} | None:
#     #     return await self.first(name=name)
'''


def _models_with_db(name: str) -> str:
    p, _, pl = _pascal(name), _snake(name), _plural(name)
    return f'''\
"""ORM model for the {p} module."""
from __future__ import annotations

from aura.orm import AuraModel, CharField
from sqlalchemy.orm import Mapped


class {p}(AuraModel):
    __tablename__ = "{pl}"

    name: Mapped[str] = CharField(max_length=150)
'''


def _repository_with_db(name: str) -> str:
    p, _, _pl = _pascal(name), _snake(name), _plural(name)
    return f'''\
"""Repository for the {p} module."""
from __future__ import annotations

from aura.orm import Repository
from .models import {p}


class {p}Repository(Repository[{p}]):
    model = {p}
'''


def _service(name: str) -> str:
    p, s, pl = _pascal(name), _snake(name), _plural(name)
    return f'''\
"""Service layer for the {p} module."""
from __future__ import annotations

from aura import injectable, NotFoundException, ConflictException, Log
from .schemas import Create{p}DTO, Update{p}DTO, {p}Response


@injectable
class {p}Service:
    """Business logic for {p} operations.

    Uses an in-memory store by default.
    To switch to a database, register {p}Repository in the module's providers,
    and inject it:

        from .repositories import {p}Repository

        def __init__(self, repo: {p}Repository) -> None:
            self.repo = repo

        async def list_{pl}(self) -> list[{p}Response]:
            rows = await self.repo.list()
            return [{p}Response.model_validate(r.to_dict()) for r in rows]
    """

    def __init__(self) -> None:
        self._store: dict[int, {p}Response] = {{}}
        self._next_id = 1

    async def list_{pl}(self) -> list[{p}Response]:
        Log.info("Listing {pl} from store")
        return list(self._store.values())

    async def get_{s}(self, {s}_id: int) -> {p}Response:
        Log.info("Fetching {s}", {s}_id={s}_id)
        obj = self._store.get({s}_id)
        if obj is None:
            raise NotFoundException(f"{p} {{{s}_id}} not found")
        return obj

    async def create_{s}(self, data: Create{p}DTO) -> {p}Response:
        obj = {p}Response(id=self._next_id, **data.model_dump())
        self._store[self._next_id] = obj
        self._next_id += 1
        return obj

    async def update_{s}(self, {s}_id: int, data: Update{p}DTO) -> {p}Response:
        obj = await self.get_{s}({s}_id)
        updated = obj.model_copy(update=data.model_dump(exclude_none=True))
        self._store[{s}_id] = updated
        return updated

    async def delete_{s}(self, {s}_id: int) -> None:
        await self.get_{s}({s}_id)
        del self._store[{s}_id]
'''


def _controller(name: str) -> str:
    p, s, pl = _pascal(name), _snake(name), _plural(name)
    return f'''\
"""Controller for the {p} module."""
from __future__ import annotations

from aura import get, post, put, delete, Body, Param, Log
from .schemas import Create{p}DTO, Update{p}DTO, {p}Response
from .service import {p}Service


class {p}Controller:
    """HTTP handlers for /{pl} routes."""

    def __init__(self, service: {p}Service) -> None:
        self.service = service  # injected by DI container

    @get("/")
    async def list_{pl}(self) -> list[{p}Response]:
        """List all {pl}."""
        Log.info("HTTP request to list {pl}")
        return await self.service.list_{pl}()

    @get("/{{{s}_id}}")
    async def get_{s}(
        self,
        {s}_id: int,
    ) -> {p}Response:
        """Get a {s} by ID."""
        return await self.service.get_{s}({s}_id)

    @post("/", status=201)
    async def create_{s}(
        self,
        body: Body[Create{p}DTO],
    ) -> {p}Response:
        """Create a new {s}."""
        return await self.service.create_{s}(body)

    @put("/{{{s}_id}}")
    async def update_{s}(
        self,
        {s}_id: int,
        body:   Body[Update{p}DTO],
    ) -> {p}Response:
        """Update a {s}."""
        return await self.service.update_{s}({s}_id, body)

    @delete("/{{{s}_id}}", status=204)
    async def delete_{s}(
        self,
        {s}_id: int,
    ) -> None:
        """Delete a {s}."""
        await self.service.delete_{s}({s}_id)
'''


def _module(name: str) -> str:
    p, _, pl = _pascal(name), _snake(name), _plural(name)
    return f'''\
"""Module declaration for the {p} feature."""
from aura import Module
from .controller import {p}Controller
from .service import {p}Service


@Module(
    providers=[{p}Service],
    controllers=[{p}Controller],
    prefix="/{pl}",
    tags=["{p}"],
)
class {p}Module:
    pass
'''


def _guard(name: str) -> str:
    p = _pascal(name)
    return f'''\
"""Guard: {p}Guard."""
from __future__ import annotations

from aura import Guard
from starlette.requests import Request


class {p}Guard(Guard):
    """Controls access to protected routes.

    Return True to allow, False to deny (responds with 403).

    Usage::

        @get("/protected", guards=[{p}Guard()])
        async def protected_route(self) -> ...:
            ...

        # Or module-wide:
        @Module(guards=[{p}Guard()], ...)
        class SecureModule: ...
    """

    async def can_activate(self, request: Request) -> bool:
        # TODO: implement your authorization logic here
        # Examples:
        #   - Check JWT:  token = request.headers.get("Authorization")
        #   - Check role: return request.state.user.role == "admin"
        return True
'''


def _test_resource(name: str) -> str:
    p, s, pl = _pascal(name), _snake(name), _plural(name)
    return f'''\
"""Integration tests for the {p} module."""
from __future__ import annotations

import pytest


async def test_list_{pl}(client):
    r = await client.get("/{pl}/")
    assert r.status_code == 200
    assert isinstance(r.json(), list)


async def test_create_{s}(client):
    r = await client.post("/{pl}/", json={{"name": "Test {p}"}})
    assert r.status_code == 201
    data = r.json()
    assert data["name"] == "Test {p}"
    assert "id" in data


async def test_get_{s}(client):
    created = await client.post("/{pl}/", json={{"name": "Get Test"}})
    {s}_id = created.json()["id"]

    r = await client.get(f"/{pl}/{{{s}_id}}")
    assert r.status_code == 200
    assert r.json()["id"] == {s}_id


async def test_get_{s}_not_found(client):
    r = await client.get("/{pl}/99999")
    assert r.status_code == 404


async def test_update_{s}(client):
    created = await client.post("/{pl}/", json={{"name": "Before"}})
    {s}_id = created.json()["id"]

    r = await client.put(f"/{pl}/{{{s}_id}}", json={{"name": "After"}})
    assert r.status_code == 200
    assert r.json()["name"] == "After"


async def test_delete_{s}(client):
    created = await client.post("/{pl}/", json={{"name": "To Delete"}})
    {s}_id = created.json()["id"]

    r = await client.delete(f"/{pl}/{{{s}_id}}")
    assert r.status_code == 204

    r = await client.get(f"/{pl}/{{{s}_id}}")
    assert r.status_code == 404
'''


# ---------------------------------------------------------------------------
# Write helper
# ---------------------------------------------------------------------------

def _write(path: Path, content: str, force: bool) -> bool:
    if path.exists() and not force:
        console.print(f"  [yellow]skip[/]   {path}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    console.print(f"  [green]create[/] {path}")
    return True


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

@app.command("module")
def generate_module(
    name:    str  = typer.Argument(..., help="Module name (e.g. 'posts', 'blog-posts')"),
    output:  str  = typer.Option("modules", "--out", "-o", help="Output base directory"),
    force:   bool = typer.Option(False, "--force", "-f", help="Overwrite existing files"),
    tests:   bool = typer.Option(True,  "--tests/--no-tests", help="Also generate test file"),
    with_db: bool = typer.Option(False, "--with-db", help="Uncomment ORM model and repository"),
) -> None:
    """Generate a complete module: schemas, service, controller, module.py."""
    s = _snake(name)
    base = Path(output) / s
    p = _pascal(name)

    console.print(f"\n[bold]Generating module [cyan]{p}[/]...[/]\n")

    models_content = _models_with_db(name) if with_db else _models(name)
    repo_content = _repository_with_db(name) if with_db else _repository(name)

    files = {
        base / "__init__.py":      f'"""Module: {p}."""\n',
        base / "models.py":        models_content,
        base / "schemas.py":       _schemas(name),
        base / "repositories.py":  repo_content,
        base / "service.py":       _service(name),
        base / "controller.py":    _controller(name),
        base / "module.py":        _module(name),
    }
    for path, content in files.items():
        _write(path, content, force)

    if tests:
        test_path = Path("tests") / f"test_{s}.py"
        _write(test_path, _test_resource(name), force)

    console.print()
    if with_db:
        console.print(
            f"[bold green]✓ Module [cyan]{p}[/] created at {base}"
            " (--with-db: ORM model and repository activated)[/]"
        )
    else:
        console.print(f"[bold green]✓ Module [cyan]{p}[/] created at {base}[/]")
    console.print()
    console.print("[bold]Register it in main.py:[/]")
    console.print(f"  [cyan]from {base!s}.module import {p}Module[/]")
    console.print(f"  [cyan]app = Aura(modules=[..., {p}Module], ...)[/]")


@app.command("controller")
def generate_controller(
    name:   str  = typer.Argument(..., help="Controller name (e.g. 'users')"),
    output: str  = typer.Option(".", "--out", "-o", help="Output directory"),
    force:  bool = typer.Option(False, "--force", "-f", help="Overwrite if exists"),
) -> None:
    """Generate a Controller class with CRUD route handlers."""
    s = _snake(name)
    path = Path(output) / f"{s}_controller.py"
    console.print(f"\n[bold]Generating controller [cyan]{_pascal(name)}Controller[/]...[/]\n")
    _write(path, _controller(name), force)
    console.print(f"\n[bold green]✓ Controller written to {path}[/]")


@app.command("service")
def generate_service(
    name:   str  = typer.Argument(..., help="Service name (e.g. 'users')"),
    output: str  = typer.Option(".", "--out", "-o", help="Output directory"),
    force:  bool = typer.Option(False, "--force", "-f", help="Overwrite if exists"),
) -> None:
    """Generate an injectable Service class with CRUD methods."""
    s = _snake(name)
    path = Path(output) / f"{s}_service.py"
    console.print(f"\n[bold]Generating service [cyan]{_pascal(name)}Service[/]...[/]\n")
    _write(path, _service(name), force)
    console.print(f"\n[bold green]✓ Service written to {path}[/]")


@app.command("schema")
def generate_schema(
    name:   str  = typer.Argument(..., help="Schema name (e.g. 'product')"),
    output: str  = typer.Option(".", "--out", "-o", help="Output directory"),
    force:  bool = typer.Option(False, "--force", "-f", help="Overwrite if exists"),
) -> None:
    """Generate Pydantic DTO schemas (Create, Update, Response)."""
    s = _snake(name)
    path = Path(output) / f"{s}_schemas.py"
    console.print(f"\n[bold]Generating schemas for [cyan]{_pascal(name)}[/]...[/]\n")
    _write(path, _schemas(name), force)
    console.print(f"\n[bold green]✓ Schemas written to {path}[/]")


@app.command("guard")
def generate_guard(
    name:   str  = typer.Argument(..., help="Guard name (e.g. 'auth', 'admin-only')"),
    output: str  = typer.Option(".", "--out", "-o", help="Output directory"),
    force:  bool = typer.Option(False, "--force", "-f", help="Overwrite if exists"),
) -> None:
    """Generate a Guard class stub for authorization."""
    s = _snake(name)
    path = Path(output) / f"{s}_guard.py"
    console.print(f"\n[bold]Generating guard [cyan]{_pascal(name)}Guard[/]...[/]\n")
    _write(path, _guard(name), force)
    console.print(f"\n[bold green]✓ Guard written to {path}[/]")


@app.command("resource")
def generate_resource(
    name:    str  = typer.Argument(..., help="Resource name (e.g. 'post', 'product')"),
    output:  str  = typer.Option("modules", "--out", "-o", help="Output base directory"),
    force:   bool = typer.Option(False, "--force", "-f", help="Overwrite existing files"),
    tests:   bool = typer.Option(True,  "--tests/--no-tests", help="Also generate test file"),
    with_db: bool = typer.Option(False, "--with-db", help="Uncomment ORM model and repository"),
) -> None:
    """Generate a complete CRUD resource (same as 'module' with verbose output).

    Shortcut for: schemas + service + controller + module + tests.
    """
    generate_module(name=name, output=output, force=force, tests=tests, with_db=with_db)


@app.command("factory")
def generate_factory(
    name:   str  = typer.Argument(..., help="Model name for the factory (e.g. 'product', 'user')"),
    output: str  = typer.Option("database/factories", "--out", "-o", help="Output directory"),
    force:  bool = typer.Option(False, "--force", "-f", help="Overwrite if exists"),
) -> None:
    """Generate a Model Factory skeleton with Faker."""
    s = _snake(name)
    path = Path(output) / f"{s}_factory.py"
    console.print(f"\n[bold]Generating factory for [cyan]{_pascal(name)}[/]...[/]\n")
    _write(path, _factory(name), force)
    console.print(f"\n[bold green]✓ Factory written to {path}[/]")


@app.callback(invoke_without_command=True)
def _list_commands(ctx: typer.Context) -> None:
    """Generate Aura resources."""
    if ctx.invoked_subcommand is None:
        table = Table(title="Available generators", show_header=True)
        table.add_column("Command",     style="cyan")
        table.add_column("What it creates")
        table.add_row("module <name>",     "schemas + service + controller + module.py + tests")
        table.add_row("resource <name>",   "same as module (alias)")
        table.add_row("controller <name>", "controller class with CRUD handlers")
        table.add_row("service <name>",    "@injectable service class with CRUD methods")
        table.add_row("schema <name>",     "Create/Update/Response Pydantic schemas")
        table.add_row("guard <name>",      "Guard class stub for authorization")
        table.add_row("factory <name>",    "Factory class skeleton for Model and Faker")
        console.print(table)
        console.print()
        console.print("[dim]Example: [cyan]aura generate module posts[/][/]")
